import React, { useEffect } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Typography, Box, Link, Button, Container, Grid } from '@mui/material'
import { Breakpoint } from '@mui/system';;

const CONTAINER_MAX_SIZE_VALUES: Breakpoint[] = ['xl', 'lg', 'md', 'sm', 'xs']

type HomeProps = {
  toggleTheme?: React.MouseEventHandler<HTMLButtonElement>;
}

const Home = (props: HomeProps) => {
  const [containerMaxSize, setContainerMaxSize] = React.useState<number>(0);

  const toggleContainerSize = () => {
    let newContainerMaxSizeValue = containerMaxSize + 1;
    
    if(containerMaxSize + 1 > 4) {
      newContainerMaxSizeValue = 0;
    }

    setContainerMaxSize(newContainerMaxSizeValue);
  }; 

  useEffect(() => {
    console.log(containerMaxSize);


  }, [containerMaxSize]);

  return (
    <Box
      sx={{
        backgroundColor: 'background.paper'
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container maxWidth={CONTAINER_MAX_SIZE_VALUES[containerMaxSize]}>
          <Typography variant={'h2'} ml={2} mr={2}>
            Welcome to <a href="https://nextjs.org">MUI with NextJs Demo!</a>
          </Typography>

          <Grid container mb={2}>
            <Grid item xs={6} md={3} lg={2}>
              <Button
                onClick={props.toggleTheme}  
                color={'info'}
              >
                Toggle Theme
              </Button>
            </Grid>
            <Grid item xs={6} md={3} lg={2}>
              <Button
                onClick={toggleContainerSize as any}
                color={'info'}
              >
                Toggle Container Size
              </Button>
            </Grid>
          </Grid>

          <Grid container>
            <Grid item xs={12} md={6} lg={3}>
              <Link href="https://nextjs.org/docs">
                <Typography variant={'h6'}>Documentation &rarr;</Typography>
                <Typography variant={'body1'}>Find in-depth information about Next.js features and API.</Typography>
              </Link>
            </Grid>
            <Grid item xs={12} md={6} lg={3}>
              <Link href="https://nextjs.org/learn">
                <Typography variant={'h6'}>Learn &rarr;</Typography>
                <Typography variant={'body1'}>Learn about Next.js in an interactive course with quizzes!</Typography>
              </Link>
            </Grid>
            <Grid item xs={12} md={6} lg={3}>
              <Link
                href="https://github.com/vercel/next.js/tree/master/examples"
              >
                <Typography variant={'h6'}>Examples &rarr;</Typography>
                <Typography variant={'body1'}>Discover and deploy boilerplate example Next.js projects.</Typography>
              </Link>
            </Grid>
            <Grid item xs={12} md={6} lg={3}>
              <Link
                href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              >
                <Typography variant={'h6'}>Deploy &rarr;</Typography>
                <Typography variant={'body1'}>
                  Instantly deploy your Next.js site to a public URL with Vercel.
                </Typography>
              </Link>
            </Grid>
          </Grid>
          <Box>



          </Box>
        </Container>
      </main>

      <Box>
        <footer>
          <Link
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            align={'center'}
          >
            <Typography variant={'caption'} align='center'>
              Powered by{' '}
              <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
              </span>
            </Typography>
          </Link>
        </footer>
      </Box>
    </Box>

  )
}

export default Home
